#!/bin/bash
#
#PBS -W group_list=yetiphyso
#PBS -N basin32
#PBS -l nodes=1:ppn=4:ib2,walltime=12:00:00,mem=16000mb
#PBS -m abe

RUNDIR=$PBS_O_WORKDIR

echo "Running MITgcm in $RUNDIR"
cd $RUNDIR

module add intel-parallel-studio/2015
mpirun -n 4 ./mitgcmuv

